# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0003_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel_app.Room'),
            preserve_default=False,
        ),
    ]
